// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SteamNexus.Models;

public partial class ProductCategory
{
    [Key]
    public int ProductCategoryId { get; set; }

    [Required]
    [MaxLength(100)]
    public string Name { get; set; }

    public virtual ICollection<ProductInformation> ProductInformations { get; set; } = new List<ProductInformation>();
}