// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamNexus.Models;

public partial class ProductInformation
{
    public int ProductInformationId { get; set; }

    public int ProductCategoryId { get; set; }

    public string Name { get; set; }

    public string Specification { get; set; }

    public int Price { get; set; }

    public int Wattage { get; set; }

    public int? Recommend { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ICollection<ProductCpu> ProductCpus { get; set; } = new List<ProductCpu>();

    public virtual ICollection<ProductGpu> ProductGpus { get; set; } = new List<ProductGpu>();

    public virtual ICollection<ProductRam> ProductRams { get; set; } = new List<ProductRam>();
}