// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamNexus.Models;

public partial class ProductRam
{
    public int ProductRamid { get; set; }

    public int ProductInformationId { get; set; }

    public int Size { get; set; }

    public virtual ProductInformation ProductInformation { get; set; }
}