// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamNexus.Models;

public partial class ProductGpu
{
    public int ProductGpuid { get; set; }

    public int ProductInformationId { get; set; }

    public int Gpuid { get; set; }

    public virtual GPU Gpu { get; set; }

    public virtual ProductInformation ProductInformation { get; set; }
}