// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamNexus.Models;

public partial class ProductCpu
{
    public int ProductCpuid { get; set; }

    public int ProductInformationId { get; set; }

    public int Cpuid { get; set; }

    public virtual CPU Cpu { get; set; }

    public virtual ProductInformation ProductInformation { get; set; }
}