// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SteamNexus_Server.Models;
public class ProductMenu
{
    [Key]
    public int ProductMenuId { get; set; }

    [Required]
    [MaxLength(50)]
    public string MenuName { get; set; }

    #nullable enable

    public int? ProductInformationId { get; set; }

    public virtual ProductInformation? ProductInformation { get; set; }
}

