// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;

namespace SteamNexus_Server.Models;

public class MenuDetail
{
    [Key]
    public int MenuDetailId { get; set; }

    [Required]
    public string MenuDetailName { get; set; }

}
