// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SteamNexus.Models;

public partial class Game
{
    [Key]
    [Required]
    public int GameId { get; set; }

    [Required]
    public int AppId { get; set; }

    [Required]
    [MaxLength(100)]
    public string Name { get; set; }

    [Required]
    public int OriginalPrice { get; set; }

    [Required]
    public int CurrentPrice { get; set; }

    [Required]
    public int LowestPrice { get; set; }

    [Required]
    [MaxLength(100)]
    public string AgeRating { get; set; }

    [MaxLength(100)]
    public string? Comment { get; set; }

    [MaxLength(100)]
    public int? CommentNum { get; set; }

    public DateTime? ReleaseDate { get; set; }

    [MaxLength(100)]
    public string? Publisher { get; set; }

    [MaxLength(500)]
    public string? Description { get; set; }

    public int? Players { get; set; }

    public int? PeakPlayers { get; set; }

    [MaxLength(300)]
    public string? ImagePath { get; set; }

    [MaxLength(300)]
    public string? VideoPath { get; set; }

    [Required]
    public int MinReqId { get; set; }

    [Required]
    public int RecReqId { get; set; }

    public virtual ICollection<GameLanguage> GameLanguages { get; set; } = new List<GameLanguage>();

    public virtual MinimumRequirement MinReq { get; set; }

    public virtual ICollection<PlayersHistory> PlayersHistories { get; set; } = new List<PlayersHistory>();

    public virtual ICollection<PriceHistory> PriceHistories { get; set; } = new List<PriceHistory>();

    public virtual RecommendedRequirement RecReq { get; set; }

    public virtual ICollection<TagGroup> TagGroups { get; set; } = new List<TagGroup>();
}