// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamNexus.Models;

public partial class Member
{
    public int MemberId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public bool? Gender { get; set; }

    public string Phone { get; set; }

    public DateOnly? Birthday { get; set; }

    public string Photo { get; set; }

    public int Cpuid { get; set; }

    public int Gpuid { get; set; }

    public int Ram { get; set; }

    public virtual CPU Cpu { get; set; }

    public virtual ICollection<GameFollow> GameFollows { get; set; } = new List<GameFollow>();

    public virtual GPU Gpu { get; set; }
}