// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;

namespace SteamNexus.Models;

public partial class Role
{
    [Key]
    [Required]
    public int RoleId { get; set; }

    [Required]
    public int UserId { get; set; }

    [Required]
    public string RoleName { get; set; }

    public virtual User User { get; set; }

}
