// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SteamNexus.Models;

public partial class User
{
    [Key]
    [Required]
    public int UserId { get; set; }

    [Required]
    [MaxLength(100)]
    public string Email { get; set; }

    [Required]
    [MaxLength(20)]
    public string Password { get; set; }

    [Required]
    [MaxLength(50)]
    public string Name { get; set; }

    public bool? Gender { get; set; } = true;

    #nullable enable
    [MaxLength(20)]
    public string? Phone { get; set; }

    public DateTime? Birthday { get; set; }

    [MaxLength(200)]
    public string? Photo { get; set; }

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();

}
