// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SteamNexus.Models;

public partial class Users
{
    [Key]
    [Required]
    public int MemberId { get; set; }

    [Required]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    [MaxLength(20)]
    public string Password { get; set; }

    [Required]
    [MaxLength(50)]
    public string Name { get; set; }

    [Required]
    public bool? Gender { get; set; }

    [Required]
    [MaxLength(10)]
    public string Phone { get; set; }

    [Required]
    public DateOnly? Birthday { get; set; }

    [MaxLength(200)]
    public string? Photo { get; set; }

}
